version: '3'

services: 
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes: 
            - .:/var/www/app/
        ports: 
            - 8001:80
        networks: 
            - app
    php:
        build: 
            context: .
            dockerfile: Dockerfile-php
        environment: 
            APP_ENV: dev
        volumes: 
            - .:/var/www/app/
        networks: 
            - app
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_list_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: password
        volumes:
            - ./mysql/database_scripts/:/docker-entrypoint-initdb.d/
        ports:
            - "4406:3306"

networks: 
    app:
        